### ISSUE TITLE
Difference between this and builtin option?

### ISSUE THREAD

**Issue by avindra** [clessg/progress-bar-webpack-plugin#14]
Hi, 

I'm trying to understand what's the difference between this plugin and the `--progress` option available in Webpack directly.

Was this an incarnation of progress before webpack had it natively?

**Comment by clessg** [comment]
Doesn't webpack's `--progress` option simply show the % completed and # of modules built? (Such as "50% 100/200".) Or did they recently change it to show a progress bar?
