### ISSUE TITLE
Support for Webpack 3?

### ISSUE THREAD

**Issue by Retsam** [clessg/progress-bar-webpack-plugin#21]
Does this plugin support webpack 3?  According to the package.json `peerDependencies` it doesn't.  Does that just need to be updated, or are there functional changes that need to happen first?

**Comment by ai** [comment]
Everything seems working. Let’s just update `peerDependencies`.

@clessg do you need PR for it?

**Comment by Retsam** [comment]
Looks like this has been resolved.  Thanks.
