### ISSUE TITLE
When the webpack is compiling, if there is another log, will cause to two progress bar

### ISSUE THREAD

**Issue by tjx666** [clessg/progress-bar-webpack-plugin#33]
In my [project](https://github.com/tjx666/awesome-chrome-extension-boilerplate), the webpack server will log a message when server is successfully startup：

```typescript
const devServer = express();
devMiddlewares(devServer);

const { HOST, PORT } = serverConfig;
devServer.listen(PORT, HOST, async error => {
    console.log(`${chalk.green.bold('INFO')} DevServer running at ${chalk.magenta.bold.underline(address)} ${chalk.green('✓')}`);
})
```

devMiddlewares function is:

```javascript
export default (app: Express): void => {
    const compiler = webpack(devConfig);
    const devMiddlewareOptions: webpackDevMiddleware.Options = {
        //...
    };
    app.use(webpackDevMiddleware(compiler, devMiddlewareOptions));
    app.use(webpackHotMiddleware(compiler, { path: '/__webpack_HMR__' }));
};

```

I guess this bug is because when the webpack compile progress is 10%, the server callback above is call. 

![Snipaste_2019-11-26_17-11-52](https://user-images.githubusercontent.com/41773861/69618944-b90bd580-1075-11ea-8246-5febabd9a2fc.png)

**Comment by tageecc** [comment]
any updates @tjx666

**Comment by tjx666** [comment]
try https://github.com/unjs/webpackbar @tageecc

**Comment by nkappler** [comment]
can we re-open this please?
