### ISSUE TITLE
show two compiled result with total finished time in webpack5

### ISSUE THREAD

**Issue by mingyuyuyu** [clessg/progress-bar-webpack-plugin#39]
![image](https://user-images.githubusercontent.com/32156701/103845562-48881280-50d7-11eb-820a-6dcc559e4ce5.png)

**Comment by Idletalk** [comment]
Seems to be the webpack5 cache will cause the much times 1 of the percentage, so the output will have two complete.

**Comment by yanghuanrong** [comment]
I have the same problem, is there a better solution?
